### ISSUE TITLE
Tagging Feature request

### ISSUE THREAD

**Issue by ryantimjohn** [ryantimjohn/action_network_1on1_tracker#3]
Andre asked if we could add a quick way to give Action Network tags to people from the one-on-one tracker.

**Comment by smithsa** [comment]
Looks like that is not possible via the api. We can display them per user, and sort people by tags.
"Posting, putting, and deleting tags is not allowed. Attempts will result in errors."
https://actionnetwork.org/docs/v2/tags

**Comment by ryantimjohn** [comment]
Saddest of sad faces. =(((
